// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnwflndfihoaayvalggi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxud2ZsbmRmaWhvYWF5dmFsZ2dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxNzU3MDAsImV4cCI6MjA5NDc1MTcwMH0.plzus5T0H6QnQpdcFn-6bXIxsQbZ0cK8WtmHq8GitFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});